import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import GoogleMapsProvider from "./components/GoogleMapsProvider";

const inter = Inter({ subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Handy | Main page",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

// layout remains a Server Component; GoogleMapsProvider is a Client Component

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <header className="flex items-center justify-between px-8 py-4 border-b border-gray-200 bg-white">
          <Link href="/" className="text-4xl font-bold text-[#FF7A00]">
            Handy
          </Link>
          <nav className="flex gap-6 text-gray-600">
            <Link href="/przegladaj" className="hover:text-[#FF7A00] transition py-4">
              Przeglądaj
            </Link>
            <Link href="/addRequest" className="hover:text-[#FF7A00] transition py-4">
              Dodaj ogłoszenie
            </Link>
            <Link
              href="/login"
              className="bg-[#FF7A00] text-white px-4 py-4 rounded hover:bg-[#E86A00] transition"
            >
              Zaloguj się
            </Link>
          </nav>
        </header>
        <GoogleMapsProvider>
          <main>{children}</main>
        </GoogleMapsProvider>
      </body>
    </html>
  );
}
